package com.finddr.exception;

public enum ErrorCode {
    // User/Auth
    USER_NOT_FOUND,
    USER_ALREADY_EXIST,
    INVALID_CREDENTIALS,
    UNAUTHORIZED_ACCESS,
    FORBIDDEN_ACTION,
    ACCOUNT_INACTIVE,
    INVALID_TOKEN,
    USER_INACTIVE,
    INADEQUATE_DOCTOR_DATA,

    // Appointments
    APPOINTMENT_NOT_FOUND,
    APPOINTMENT_CONFLICT,
    DOCTOR_HAS_NO_CLINIC,
    DOCTOR_NOT_AVAILABLE,
    INVALID_APPOINTMENT_SLOT,
    PATIENT_ALREADY_BOOKED,
    DOCTOR_NOT_FOUND,

    SCHEDULE_NOT_FOUND,
    // Payments
    PAYMENT_FAILED,
    INVALID_PAYMENT_MODE,
    BILLING_ERROR,
    REFUND_FAILED,

    // Medical
    PRESCRIPTION_NOT_FOUND,
    INVALID_PRESCRIPTION_DATA,
    MEDICAL_RECORD_ACCESS_DENIED,

    // Generic
    INTERNAL_ERROR,
    INVALID_INPUT,
    VALIDATION_ERROR,
    RESOURCE_CONFLICT,
    SERVICE_UNAVAILABLE,
    FILE_UPLOAD_ERROR,
    S3_DELETE_FAILED,
}
