package com.finddr.exception;

public enum ErrorCode {
  // User/Auth
  USER_NOT_FOUND,
  USER_ALREADY_EXIST,
  INVALID_CREDENTIALS,
  UNAUTHORIZED_ACCESS,
  FORBIDDEN_ACTION,
  ACCOUNT_INACTIVE,
  INVALID_TOKEN,
  USER_INACTIVE,

  // Appointments
  APPOINTMENT_NOT_FOUND,
  APPOINTMENT_CONFLICT,
  DOCTOR_NOT_AVAILABLE,
  INVALID_APPOINTMENT_SLOT,
  PATIENT_ALREADY_BOOKED,

  // Payments
  PAYMENT_FAILED,
  INVALID_PAYMENT_MODE,
  BILLING_ERROR,
  REFUND_FAILED,

  // Medical
  PRESCRIPTION_NOT_FOUND,
  INVALID_PRESCRIPTION_DATA,
  MEDICAL_RECORD_ACCESS_DENIED,

  // Generic
  INTERNAL_ERROR,
  VALIDATION_ERROR,
  RESOURCE_CONFLICT,
  SERVICE_UNAVAILABLE
}
